config_version: 0

authors:
- Pixar

name: ptex

version: 2.0.62

description: "Ptex"

variants:
- ["Linux"]

uuid: "repository.ptex"

commands:
- export CMAKE_MODULE_PATH=$CMAKE_MODULE_PATH:!ROOT!/cmake
- export PATH=!ROOT!/bin:$PATH
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:!ROOT!/lib
